driverClassName=com.mysql.cj.jdbc.Driver
url=jdbc:mysql:///library_management?usuSSL=false&useServerPreStmts=true
username=root
password=1219
# ??????
initialSize=5
# ??????
maxActive=10
# ??????
maxWait=3000